### PR TITLE
Added Raleway Font

### PR DESCRIPTION
**Pull request by ghost**
Tagging @Rafase282 @raisedadead

### CODE REVIEW

**Comment by Rafase282** [comment]
If I remember correctly, google servers are blocked in China. Please check if we are using alternatives to that or not.

**Comment by Rafase282** [comment]
If the page is over http then it is fine, otherwise you should try to use a secure link instead.

**Comment by ghost** [comment]
@Rafase282 Yeh I tried. They one support `http` :sob:

**Comment by Rafase282** [comment]
I'm pretty sure `https` is preferred if not needed.

Take a look at https://www.fontsquirrel.com/fonts/raleway

**Comment by ghost** [comment]
@Rafase282 Should we host the fonts ourselves so no issue with cloudflare?

**Comment by Rafase282** [comment]
@theflametrooper yes we could as far as I know. I'm waiting on a reply to https://github.com/FreeCodeCamp/FreeCodeCamp/issues/8314 to see if you can add that one instead and then merge.

**Comment by Rafase282** [comment]
I think it would be better to just change to the font @QuincyLarson said we should use. Please just update to add the right font in this PR.

**Comment by ghost** [comment]
Closing, we're switching to using the `Lato` font instead.

**Pull request closed without merging**
