### PR TITLE
Fix Wiki Generator for Linux and improves it

### LINKED ISSUE #4: Alternative to typography?
Any chance that `typography` can be switched to something else? Me and @hallaathrad tried to set it up locally on my raspberry pi witch raspbian and that particular part of the script is what prevented it from working.

### LINKED ISSUE #10: Update Wiki Readme so it's easier to get wiki up and running
The wiki's README.md's directions are out of date.

Related to and closes https://github.com/FreeCodeCamp/FreeCodeCamp/issues/8317

### LINKED ISSUE #17: Wiki Generator does not work
Currently the wiki generator fails to build and update the live wiki. It seems to be related to Non English wiki languages.

### LINKED ISSUE #18: Add language folder structure
The folder structure should the following

```
"freecodecamp.com/wiki"
|- "/en"
  |- "/some-cool-article"
|- "/es"
  |- "/hola"
```

Related and closes https://github.com/FreeCodeCamp/wiki/issues/290

### PR DESCRIPTION
**Pull request by Rafase282**
# Changes:
- Remove scripts and implement them into the npm package. Run with `npm run <script name>`
- Update `Readme` with new instructions.
- Uses Regex to handle these three types of articles:
  1. `Home.md`
  2. `ES-Home.md`
  3. `PT-BR-Home.md`
- Automatically generate list of supported languages. (English is the default in the list.)
- Uses **[rimraf](https://www.npmjs.com/package/rimraf)** and **[graceful-fs](https://www.npmjs.com/package/graceful-fs#global-patching)**.
## Solves these issues:

Closes #18
Closes #17 
Closes #10 
Closes #4

### CODE REVIEW

**Comment by Rafase282** [comment]
I'll be posting the current roadblocks I encounter, if you want to help with them then contact me. As the labels says, help is appreciated.

**Comment by DanAdrenaline** [comment]
I would like to help if there is anything that you have already identified, got an hour or so now, was goning try and create a local, but I was reading on other issues there may be problems with it. Will give it a whirl anyway.

**Comment by Rafase282** [comment]
@DanAdrenaline you can send PR against my fork, right now the issue I'm having is on the description.

**Comment by Rafase282** [comment]
Currently the scripts are working, you can build and deploy. technically the PR is done. All that is left is to modify the scripts to remove double titles and others. Perhaps this should be done in a different PR.

**Pull request merged**
