### PR TITLE
Wiki Redesign: Improvements

### LINKED ISSUE #34: Wiki articles are too wide and get truncated

### LINKED ISSUE #35: Search needs obvious form input field and result box

### PR DESCRIPTION
**Pull request by Rafase282**
# Changes
- Adds solid dark green borders to the article list
- Resize search bar to look neat
- Centers article's title
- Removes padding from the left and adds margin to the right

Closes #35 
Closes #34 
## Full View

Full View
## Side View

Side View
## Mobile View

Mobile View

### CODE REVIEW

**Comment by Rafase282** [comment]
@QuincyLarson What do you think of this look? I used the same darkgreen as the navbar.

Also which browser did you use that the scrollbar was not showing? It is always showing on my end.

**Comment by ghost** [comment]
@Rafase282 I would add some padding between the box and results.

**Comment by Rafase282** [comment]
Updated preview images.

**Comment by ghost** [comment]
### **LGTM :+1:**

**Comment by justincorrigible** [comment]
Great Job, Raf!

**Pull request merged**
